### ISSUE TITLE
1. - 1e-10 == 1.

### ISSUE THREAD

**Issue by NasenSpray** [snipsco/ntm-lasagne#20]
The examples clip the outputs to an upper bound of `1. - 1e-10` before passing them to `binary_crossentropy()` (eg [here](https://github.com/snipsco/ntm-lasagne/blob/master/examples/associative-recall.py#L64-L65)). This value can't be represented as `float32` and is always rounded to 1, which might be the reason for the NaNs you're witnessing occasionally.

**Comment by tristandeleu** [comment]
Indeed thanks! I fixed it in 9f7b97b6934d3bedec7916b01511a88c14b741f2 by increasing the clipping value from `1e-10` to `1e-6`.
