### ISSUE TITLE
Question about the shifting operation in read heads

### ISSUE THREAD

**Issue by sxjscience** [snipsco/ntm-lasagne#27]
Thanks for the implementation! Really helpful for others to understand neural turing machine! I find that in the code, shifting (Eq. (8) in https://arxiv.org/pdf/1410.5401v2.pdf) seems to be implemented using pure convolution instead of circular convolution (https://github.com/snipsco/ntm-lasagne/blob/master/ntm/heads.py#L382-L390). Will this cause some problems?

**Comment by tristandeleu** [comment]
This is very true, I chose to use flat convolutions instead of circular convolutions. In my early tests, they seemed to be faster than the circular ones. In practice, this had no impact on the experiments on the algorithmic tasks.
I will add a comment to address this!

**Comment by mosassem88** [comment]
Hi tristandeleu, can you please clarify what do u mean by flat convolutions

thanks
