### ISSUE TITLE
Multiple Read Head Issue

### ISSUE THREAD

**Issue by terryrabinowitz** [snipsco/ntm-lasagne#29]
Hello again! Sorry to be a bother - I am just trying to get as much out this code as I can :)

Everything, I think, is working fine until I raise the number of reads in the controller > 1.  When I try anything higher, I get a shape mismatch error in the W (reads->hid) that is a multiple of the number of reads.  Am I missing something simple like a layer reshape?  Here is the simplest model that is giving me the error:

[model.txt](https://github.com/snipsco/ntm-lasagne/files/416726/model.txt)

And here is the error (I emboldened relevant lines):
[error.docx](https://github.com/snipsco/ntm-lasagne/files/416732/error.docx)

Thank you again,
Terry

**Comment by tristandeleu** [comment]
Your number of heads `num_reads` must match the number of reading heads `ReadHead` you define in `heads`. Something like:
```python
heads = [
    WriteHead(controller, ...),
    ReadHead(controller, ...),
    ReadHead(controller, ...)
]
```
I agree the API is not ideal, but to initialize the controller and the heads, both need informations from the other. The simplest way I could think was to have `num_reads`.
I will make this error explicit to avoid any confusion.

**Comment by terryrabinowitz** [comment]
I see now.  Thanks again!  It is working fine after I made your changes.
